version: '3.6'
services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/nginx/ssl.conf:/etc/nginx/default.d/ssl.conf
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/certificates:/etc/nginx/certificates
      - ./configs/nginx/dhparam.pem:/etc/nginx/dhparam.pem
    network_mode: host
    environment:
      - TZ='Asia/Tehran'
    restart: unless-stopped

  jira:
    image: jira:8.21.0
    environment:
      - TZ='Asia/Tehran'
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=3g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=1g'
    volumes:
      - ./homes/jira-srv:/var/jira
      - ./configs/server_conf/jira.xml:/opt/jira/conf/server.xml
    network_mode: host
    depends_on:
      - postgres-jira
    restart: always

  confluence:
    image: confluence:7.15.0
    environment:
      - TZ='Asia/Tehran'
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=3g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    volumes:
      - ./homes/confluence-srv:/var/confluence
      - ./configs/server_conf/confluence.xml:/opt/confluence/conf/server.xml
    network_mode: host
    depends_on:
      - postgres-confluence
    restart: always

  postgres-jira:
    image: postgres:11-alpine
    environment:
       TZ: 'Asia/Tehran'
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_USER: jira
       POSTGRES_DB: jira
    volumes:
       - ./databases/jira:/var/lib/postgresql/data
    network_mode: host
    restart: always

  postgres-confluence:
    image: postgres:11-alpine
    environment:
       TZ: 'Asia/Tehran'
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_USER: confluence
       POSTGRES_DB: confluence
    volumes:
       - ./databases/confluence:/var/lib/postgresql/data
    network_mode: host
    restart: always
