version: '3.7'
services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl.conf:/etc/nginx/default.d/ssl.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificates:/etc/nginx/certificates
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem
    network_mode: host
    environment:
      - TZ='Asia/Tehran'
    restart: unless-stopped

  jira:
    build:
      context: ./Dockerfile/jira
    environment:
      - TZ='Asia/Tehran'
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=4g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=1g'
    volumes:
      - ./home/jira-srv:/var/jira
      - ./server_config/jira.xml:/opt/jira/conf/server.xml
    network_mode: host
    depends_on:
      - postgres-jira
    restart: always

  confluence:
    build:
      context: Dockerfile/confluence
    environment:
      - TZ='Asia/Tehran'
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=4g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    volumes:
      - ./home/confluence-srv:/var/confluence
      - ./server_config/confluence.xml:/opt/confluence/conf/server.xml
    network_mode: host
    depends_on:
      - postgres-confluence
    restart: always

  postgres-jira:
    image: postgres:11-alpine
    environment:
       TZ: 'Asia/Tehran'
       POSTGRES_PASSWORD: ${JIRA_DB_PASSWORD}
       POSTGRES_USER: ${JIRA_DB_USERNAME}
       POSTGRES_DB: ${JIRA_DB_NAME}
    volumes:
       - ./databases/jira:/var/lib/postgresql/data
    network_mode: host
    restart: always

  postgres-confluence:
    image: postgres:11-alpine
    environment:
       TZ: 'Asia/Tehran'
       POSTGRES_PASSWORD: ${CONFLUENCE_DB_PASSWORD}
       POSTGRES_USER: ${CONFLUENCE_DB_USERNAME}
       POSTGRES_DB: ${CONFLUENCE_DB_NAME}
    volumes:
       - ./databases/confluence:/var/lib/postgresql/data
    network_mode: host
    restart: always
